version: '3.3'

services:
  database:
    container_name: service_portal_database
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: service_portal
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - '3001:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    container_name: service_portal_php
    build:
      context: ./php
    ports:
      - '3002:9000'
    volumes:
      - ./app:/var/www/service_portal
    depends_on:
      - database

  nginx:
    container_name: service_portal_nginx
    image: nginx:stable-alpine
    ports:
      - '3003:80'
    volumes:
      - ./app:/var/www/service_portal
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  frontend:
    container_name: service_portal_frontend
    build:
      context: ./frontend
    ports:
      - '3004:8080'
    volumes:
      - ./frontend:/usr/src/app/
    depends_on:
      - nginx
